### ISSUE TITLE
上传大点的文件之后就会超时

### ISSUE THREAD

**Issue by lvusyy** [xiewenya/django-aliyun-oss2-storage#1]
本地测试的时候.
`'details': "RequestError: HTTPConnectionPool(host='xx.oss-cn-hangzhou.aliyuncs.com', port=80): Read timed out. (read timeout=60)", 'status': -2`

**Comment by xiewenya** [comment]
host='xx.oss-cn-hangzhou.aliyuncs.com'
你的host配置不对请使用真实的host
