### ISSUE TITLE
你好关于DEFAULT_FILE_STORAGE和STATICFILES_STORAGE配置的疑问

### ISSUE THREAD

**Issue by jacobzheng** [xiewenya/django-aliyun-oss2-storage#10]
# mediafile将自动上传
DEFAULT_FILE_STORAGE = 'aliyun_oss2_storage.backends.AliyunMediaStorage'
# staticfile将自动上传
STATICFILES_STORAGE = 'aliyun_oss2_storage.backends.AliyunStaticStorage'

你好，这两个配置我测试出来的结果是，配置DEFAULT_FILE_STORAGE功能正常，如果再配置STATICFILES_STORAGE则页面加载资源的所有连接会添加END_POINT前缀，但是比如说配合xadmin这些框架使用的时候，资源不需要加载end_point。

另外还有一个建议，能否保存图片的时候重新命名保存？？

我具体对这两个配置的作用还没有看源码，python只懂基础语法，django大致了解models一些基础，希望能做一些精准的文档。

**Comment by xiewenya** [comment]
能否把你的具体配置，和输出结果发一下，我好定位问题

**Comment by jacobzheng** [comment]
# _*_ encoding:utf-8 _*_
"""
Django settings for online_cms project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!cmua#!%%nv!x89l&ea6#0ep!akh3*7gb6_l6gag@jccr-kl!h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "users.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'courses',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'aliyun_oss2_storage'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'online_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n'
            ],
        },
    },
]

WSGI_APPLICATION = 'online_cms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xxxxx',
        'USER': 'root',
        'PASSWORD': 'xxxxx',
        'HOST': '127.0.0.1'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('en', _('English')),
    ('zh-hans', _('中文简体')),
)

# 翻译文件所在目录，需要手工创建
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

ACCESS_KEY_ID = "xxxxxxx"
ACCESS_KEY_SECRET = "xxxxx"
END_POINT = "http://oss-cn-hangzhou.aliyuncs.com"
BUCKET_NAME = "xxxxx"
BUCKET_ACL_TYPE = "public-read" # private, public-read, public-read-write


# mediafile将自动上传
DEFAULT_FILE_STORAGE = 'aliyun_oss2_storage.backends.AliyunMediaStorage'

# staticfile将自动上传
STATICFILES_STORAGE = 'aliyun_oss2_storage.backends.AliyunStaticStorage'

以上是全部配置文件。
问题是如果加上STATICFILES_STORAGE配合xadmin使用的时候网页上的所有静态资源引用都会把阿里云的oss外网地址拼接上。xadmin引入的方式都是本地引入，所有的样式，js都失效了。

**Comment by xiewenya** [comment]
那是肯定的啊，你配置了staticfiles_storage，就是说所有的样式和js都放到阿里云上了。自然会带上end point。如果不需要的话，就把STATICFILES_STORAGE = 'aliyun_oss2_storage.backends.AliyunStaticStorage'注释掉就可以了

**Comment by xiewenya** [comment]
关于你说的修改文件名称是很好的建议，我会抽空加上去的
