### ISSUE TITLE
AliyunFile的__init__方法self._name设置会引发NoSuchKey错误，找不到OSS上的对象

### ISSUE THREAD

**Issue by NathanymousFu** [xiewenya/django-aliyun-oss2-storage#17]
这段代码会错误地赋值导致无法在OSS上找到想要的对象。
`self._name = name[len(self._storage.location):]`

由于我使用了wagtail框架，上传图片时`name`会是`'original_image/01.jpg'`，而`self._storage.location`我的设置是`'/res/upload/'`，这段代码`self._name`就被赋值为诡异的‘'mage/01.jpg''，这样在OSS上找不到对应的对象。

实际上`self._name`应该赋值为`'res/upload/original_image/01.jpg'`

所以这里应该写为：
```
        self._name = self._storage.location + name
        self._name = self._name.lstrip('/') 
```

麻烦看下对不对

**Comment by xiewenya** [comment]
你好，出错的原因是因为你用的wagtail框架用的相对路径。我没用过这个框架，不知道这个框架能否设置为使用绝对路径？

你这段代码是解决了相对路径的问题，但是会导致使用绝对路径的框架出错。也许可以在配置文件里加一个是否是绝对路径的配置

**Comment by NathanymousFu** [comment]
你好，搜了下wagtail貌似没有使用绝对路径的配置，这样更改可能只能符合我的情况了。

还有一个疑惑，假设还是上面的例子，如果现在使用绝对路径的框架，`self._name`的会被赋值为`'original_image/01.jpg'`吧，它不应该是`'res/upload/original_image/01.jpg'`吗？这样能够正确上传或下载吗？
绝对路径的情况：
```
name: '/res/upload/original_image/01.jpg'
self._storage.location: '/res/upload/'
self._name: 'original_image/01.jpg'
```

**Comment by manlife2017** [comment]
这个问题应该如何解决
