### ISSUE TITLE
AliyunFile中read方法获取图片后没有正确赋值

### ISSUE THREAD

**Issue by NathanymousFu** [xiewenya/django-aliyun-oss2-storage#18]
```
content = self._storage.bucket.get_object(self._name)
self.file = six.BytesIO(content)
```

这里的`content`是`oss2.models.GetObjectResult`对象，直接作为参数传给`six.BytesIO()`会返回类似于`'<oss2.models.GetObjectResult object at 0x7f59ddc0f250>'`这样的字符串，导致无法读取图片。

传给`six.BytesIO()`的应该为`content.read()`

**Comment by xiewenya** [comment]
多谢， 你可以提交一下pull request
