### ISSUE TITLE
url 被二次encoding

### ISSUE THREAD

**Issue by esr-taobao** [xiewenya/django-aliyun-oss2-storage#2]
我檔案名稱是
`/2016-07-21/小米5钢化膜_sales_False_mobile_ranking/item`

出來的url是
`http://...oss-cn-shanghai.aliyuncs.com/2016-07-21%2F%25E5%25B0%258F%25E7%25B1%25B35%25E9%2592%25A2%25E5%258C%2596%25E8%2586%259C_sales_False_mobile_ranking%2Fitems`

檔案路徑被 urlencode 2 次

**Comment by xiewenya** [comment]
不好意思，才看到。问题解决了么？
